FROM wordpress:cli

USER root

# Устанавливаем всё необходимое
RUN apk add --no-cache \
	bash \
	curl \
	unzip \
	git \
	mariadb-client

# Копируем скрипт
COPY wp-init.sh /usr/local/bin/wp-init.sh

RUN sed -i 's/\r$//' /usr/local/bin/wp-init.sh

# Делаем исполняемым
RUN chmod +x /usr/local/bin/wp-init.sh

# Рабочая директория WP
WORKDIR /var/www/html

# Гарантируем использование bash
SHELL ["/bin/bash", "-c"]

# Явный entrypoint
ENTRYPOINT ["/usr/local/bin/wp-init.sh"]
