FROM wordpress:cli

WORKDIR /var/www/html

USER root

# Alpine package manager
RUN apk add --no-cache git unzip bash

# wp-init
COPY wp-init.sh /usr/local/bin/wp-init.sh
RUN chmod 755 /usr/local/bin/wp-init.sh

USER www-data

ENTRYPOINT ["/usr/local/bin/wp-init.sh"]