version: "3.9"

services:
    database:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        volumes:
            - db:/var/lib/mysql
        networks:
            - ragu-network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD --silent",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 40s

    wordpress:
        image: wordpress:6.9.4-php8.2-apache
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: ${DATABASE_USER}
            WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
            WORDPRESS_DB_NAME: ${DATABASE_NAME}
        volumes:
            - wordpress:/var/www/html
            - ./wp-content/themes/ragu:/var/www/html/wp-content/themes/ragu
            - ./restore-updraft-google.php:/var/www/html/restore-updraft-google.php
        networks:
            - ragu-network
        depends_on:
            database:
                condition: service_healthy
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -s http://localhost/wp-login.php > /dev/null || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 40s
        user: "33:33"

    wp-init:
        build:
            context: .
            dockerfile: Dockerfile.wp-init
        networks:
            - ragu-network
        volumes:
            - wordpress:/var/www/html
            - ./wp-content/themes/ragu:/var/www/html/wp-content/themes/ragu
            - ./restore-updraft-google.php:/var/www/html/restore-updraft-google.php
        depends_on:
            wordpress:
                condition: service_healthy
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: ${DATABASE_USER}
            WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
            WORDPRESS_DB_NAME: ${DATABASE_NAME}
            UPDRAFT_GOOGLE_REFRESH_TOKEN: ${UPDRAFT_GOOGLE_REFRESH_TOKEN}
            UPDRAFT_GOOGLE_FOLDER: "UpdraftPlus"
        user: "33:33"

volumes:
    wordpress:
    db:

networks:
    ragu-network:
