services:
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - wp-network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "mysql -uroot -p${DATABASE_ROOT_PASSWORD} -e 'SELECT 1;' >/dev/null 2>&1",
                ]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 10s
        profiles:
            - core
            - setup

    wordpress:
        depends_on:
            db:
                condition: service_healthy
        image: wordpress:6.9.4-php8.2-apache
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DATABASE_USER}
            WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
            WORDPRESS_DB_NAME: ${DATABASE_NAME}
        volumes:
            - wp_data:/var/www/html
            - ./wp-content/themes/ragu:/var/www/html/wp-content/themes/ragu
        networks:
            - wp-network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    'php -r "require ''/var/www/html/wp-load.php''; echo ''OK'';" >/dev/null 2>&1',
                ]
            interval: 5s
            timeout: 3s
            retries: 20
            start_period: 20s
        profiles:
            - core
            - setup

    wpcli:
        build:
            dockerfile: Dockerfile.wpcli
        user: root
        depends_on:
            db:
                condition: service_healthy
            wordpress:
                condition: service_healthy
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${DATABASE_USER}
            WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
            WORDPRESS_DB_NAME: ${DATABASE_NAME}
            WORDPRESS_URL: ${WORDPRESS_URL}
            WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
        volumes:
            - wp_data:/var/www/html
            - ./wp-init.sh:/usr/local/bin/wp-init.sh
            - ./wp-content/themes/ragu:/var/www/html/wp-content/themes/ragu
        networks:
            - wp-network
        profiles:
            - setup
        command: ["bash", "/usr/local/bin/wp-init.sh"]

volumes:
    db_data:
    wp_data:

networks:
    wp-network:
