import { IReview } from '@/components/review';

export const reviews: IReview[] = [
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
	{
		name: 'Ирина Машова',
		gender: 'female',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: '2gis',
		rate: 4,
	},
	{
		name: 'Станислав Крид',
		gender: 'male',
		comment: 'Отличное место для приятного вечера. Приду еще',
		source: 'yandex',
		rate: 5,
	},
];
